### ISSUE TITLE
TODO: for remember

### ISSUE THREAD

**Issue by luclissi** [supermock/kpf#1]
@supermock 

- [x] add dependencies for run
- [x] check if there are file `~/.config/kube_port_forwardrc`
- [x] if pass the address get resource name from next column  

Just that, for now!
